// This file is autogenerated. Changes will be overwritten.
#include "PRMOGMWJPH/moc_AutoSwitchManager.cpp"
#include "PRMOGMWJPH/moc_DeviceManager.cpp"
#include "PRMOGMWJPH/moc_HidHideManager.cpp"
#include "UFQQIFJZKK/moc_PwaServer.cpp"
