
set(target "GremblingEx")
set(working_dir "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0")
set(src_and_dest_list
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/src/qml/main.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/build-release/GremblingEx/src/qml/main.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/src/qml/Theme.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/build-release/GremblingEx/src/qml/Theme.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/src/qml/TopHeader.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/build-release/GremblingEx/src/qml/TopHeader.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/src/qml/TopHeaderButton.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/build-release/GremblingEx/src/qml/TopHeaderButton.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/src/qml/WindowControls.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/build-release/GremblingEx/src/qml/WindowControls.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/src/qml/ScreenPlaceholder.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/build-release/GremblingEx/src/qml/ScreenPlaceholder.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/src/qml/ProfileEditorView.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/build-release/GremblingEx/src/qml/ProfileEditorView.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/src/qml/DeviceCard.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/build-release/GremblingEx/src/qml/DeviceCard.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/src/qml/InputRow.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/build-release/GremblingEx/src/qml/InputRow.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/src/qml/Badge.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/build-release/GremblingEx/src/qml/Badge.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/src/qml/CurveEditorView.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/build-release/GremblingEx/src/qml/CurveEditorView.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/src/qml/CurveHandle.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/build-release/GremblingEx/src/qml/CurveHandle.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/src/qml/DeviceTesterView.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/build-release/GremblingEx/src/qml/DeviceTesterView.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/src/qml/LogConsoleView.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/build-release/GremblingEx/src/qml/LogConsoleView.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/src/qml/StarCitizenView.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/build-release/GremblingEx/src/qml/StarCitizenView.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/src/qml/ActionPickerPopup.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/build-release/GremblingEx/src/qml/ActionPickerPopup.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/src/qml/MacroEditorPopup.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/build-release/GremblingEx/src/qml/MacroEditorPopup.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/src/qml/AxisSplitterPopup.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/build-release/GremblingEx/src/qml/AxisSplitterPopup.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/src/qml/SequencePopup.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/build-release/GremblingEx/src/qml/SequencePopup.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/src/qml/SettingsView.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/build-release/GremblingEx/src/qml/SettingsView.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/src/qml/CalibrationWizardPopup.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/build-release/GremblingEx/src/qml/CalibrationWizardPopup.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/src/qml/GlassPanel.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/build-release/GremblingEx/src/qml/GlassPanel.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/src/qml/RemoteControlPopup.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/build-release/GremblingEx/src/qml/RemoteControlPopup.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/src/qml/AutoSwitchPopup.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/build-release/GremblingEx/src/qml/AutoSwitchPopup.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/src/qml/ValueSlider.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/build-release/GremblingEx/src/qml/ValueSlider.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/src/qml/ToolButton.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/build-release/GremblingEx/src/qml/ToolButton.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/src/qml/AppComboBox.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/build-release/GremblingEx/src/qml/AppComboBox.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/src/qml/ToggleSwitch.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/build-release/GremblingEx/src/qml/ToggleSwitch.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/src/qml/PointCoordinateField.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/build-release/GremblingEx/src/qml/PointCoordinateField.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/src/qml/GremblingButton.qml"
    "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/build-release/GremblingEx/src/qml/GremblingButton.qml"

)
set(timestamp_file "C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/build-release/.qt/GremblingEx_qml.txt")
