set(__QT_DEPLOY_TARGET_GremblingCore_FILE C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/build-release/libGremblingCore.a)
set(__QT_DEPLOY_TARGET_GremblingCore_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_GremblingOutput_FILE C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/build-release/libGremblingOutput.a)
set(__QT_DEPLOY_TARGET_GremblingOutput_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_GremblingProcessing_FILE C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/build-release/libGremblingProcessing.a)
set(__QT_DEPLOY_TARGET_GremblingProcessing_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_GremblingEx_FILE C:/Users/daria/.gemini/antigravity/scratch/grembling 2.0/build-release/GremblingEx.exe)
set(__QT_DEPLOY_TARGET_GremblingEx_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_GremblingEx_RUNTIME_DLLS C:/Qt/6.11.1/mingw_64/bin/Qt6QuickControls2.dll;C:/Qt/6.11.1/mingw_64/bin/Qt6QuickEffects.dll;C:/Qt/6.11.1/mingw_64/bin/Qt6QuickDialogs2.dll;C:/Qt/6.11.1/mingw_64/bin/Qt6Svg.dll;C:/Qt/6.11.1/mingw_64/bin/Qt6WebSockets.dll;C:/Qt/6.11.1/mingw_64/bin/Qt6Xml.dll;C:/Qt/6.11.1/mingw_64/bin/Qt6PrintSupport.dll;C:/Qt/6.11.1/mingw_64/bin/Qt6Widgets.dll;C:/Qt/6.11.1/mingw_64/bin/Qt6QuickDialogs2QuickImpl.dll;C:/Qt/6.11.1/mingw_64/bin/Qt6QuickControls2Impl.dll;C:/Qt/6.11.1/mingw_64/bin/Qt6QuickTemplates2.dll;C:/Qt/6.11.1/mingw_64/bin/Qt6Quick.dll;C:/Qt/6.11.1/mingw_64/bin/Qt6OpenGL.dll;C:/Qt/6.11.1/mingw_64/bin/Qt6QmlMeta.dll;C:/Qt/6.11.1/mingw_64/bin/Qt6QmlWorkerScript.dll;C:/Qt/6.11.1/mingw_64/bin/Qt6QmlModels.dll;C:/Qt/6.11.1/mingw_64/bin/Qt6Qml.dll;C:/Qt/6.11.1/mingw_64/bin/Qt6Network.dll;C:/Qt/6.11.1/mingw_64/bin/Qt6QuickDialogs2Utils.dll;C:/Qt/6.11.1/mingw_64/bin/Qt6Gui.dll;C:/Qt/6.11.1/mingw_64/bin/Qt6Core.dll)
