// This file is autogenerated. Changes will be overwritten.
#include "5QWKTM5RRA/moc_EventRouter.cpp"
#include "5QWKTM5RRA/moc_LegacyMigrator.cpp"
#include "5QWKTM5RRA/moc_MacroHandler.cpp"
#include "5QWKTM5RRA/moc_ProfileManager.cpp"
#include "5QWKTM5RRA/moc_SCIntegrationManager.cpp"
#include "5QWKTM5RRA/moc_TempoHandler.cpp"
