#pragma once

#include <QByteArray>
#include <QHash>
#include <QObject>
#include <QSet>
#include <QString>

class QJsonObject;
class QTcpServer;
class QTcpSocket;
class QTimer;

/**
 * @brief Fase 19 (Script Bridge): localhost-only TCP transport between
 *        Nexus and externally-run Python script processes.
 *
 * Deliberately plain TCP with one JSON object per line (`\n`-delimited),
 * NOT WebSocket like PwaServer - a script's own `nexus_bridge` SDK needs to
 * stay 100% Python stdlib (`socket` + `json`), since Python has no built-in
 * WebSocket client and requiring `pip install websockets` would be real
 * friction for a community used to copying a single-file Joystick Gremlin
 * plugin and running it. See MasterPlan.md's own Fase 19 entry for the full
 * rationale and every other design decision this class implements.
 *
 * Binds ONLY to 127.0.0.1, never 0.0.0.0 - unlike PwaServer (meant to be
 * reached from a phone/tablet on the LAN), a script always runs on the same
 * machine, so there is no reason for this socket to ever be reachable from
 * outside it.
 *
 * One shared server accepts connections from potentially several script
 * processes at once, exactly like PwaServer accepts several PWA clients -
 * but unlike PwaServer's single typed-by-a-human PIN, each script instead
 * authenticates with its OWN per-launch token (see registerScriptToken()),
 * generated by whoever is about to spawn that script's QProcess and handed
 * to it via an environment variable, never typed by the user. This is
 * purely a transport/auth layer - it knows nothing about "axisState"/
 * "setAxis"/named aliases (the actual Script Bridge protocol content); that
 * belongs to whatever future layer builds JSON messages and calls
 * sendToScript()/listens to messageReceived().
 *
 * Not wired into main.cpp yet (Fase 19 implementation step 1 - see
 * MasterPlan.md) - this class compiles and is fully self-contained, but
 * nothing in the app currently constructs or starts one, so its existence
 * changes no runtime behavior for anyone.
 */
class ScriptBridgeServer : public QObject
{
    Q_OBJECT

public:
    explicit ScriptBridgeServer(QObject *parent = nullptr);
    ~ScriptBridgeServer() override;

    /// Starts listening on 127.0.0.1 with an OS-assigned ephemeral port
    /// (port 0) - see MasterPlan.md's own note on why ephemeral was chosen
    /// over a fixed port (multiple scripts, no fixed-port collision risk
    /// with anything else running locally). Safe to call while already
    /// running - stops first. Returns false (and logs via qWarning) if the
    /// bind itself failed.
    bool start();

    /// Stops listening and disconnects every currently-connected script,
    /// without revoking any still-registered tokens (a caller that wants a
    /// clean slate should also call unregisterScriptToken() for each one).
    void stop();

    bool isRunning() const;

    /// 0 if not currently listening.
    quint16 port() const;

    /// Generates and remembers a fresh token a not-yet-launched script can
    /// authenticate with once it connects - call this, hand the result to
    /// the QProcess (e.g. via env var), then launch it. Distinct tokens per
    /// script (not one shared secret like PwaServer's PIN) so
    /// messageReceived()/sendToScript() can tell multiple concurrently-
    /// connected scripts apart.
    QString registerScriptToken();

    /// Revokes a token - an already-connected client using it is
    /// disconnected immediately; a future connection attempt with it is
    /// rejected. Call this once a script's QProcess has been stopped/has
    /// exited, so a stale token can't be reused by anything else.
    void unregisterScriptToken(const QString &token);

    /// Sends message (one compact JSON object, `\n`-terminated) to
    /// whichever currently-connected, authenticated client is using this
    /// token. A no-op (not an error) if that script isn't - yet, or
    /// anymore - connected; the caller doesn't need to track connection
    /// state itself to call this safely.
    void sendToScript(const QString &token, const QJsonObject &message);

signals:
    /// Emitted once a connection using a registered token authenticates
    /// successfully.
    void scriptConnected(const QString &token);

    /// Emitted when a previously-authenticated script's connection closes,
    /// for any reason (script process exited, crashed, or Nexus itself
    /// called stop()/unregisterScriptToken() on it).
    void scriptDisconnected(const QString &token);

    /// Emitted once per line successfully parsed as a JSON object from an
    /// authenticated script's socket - message content (e.g. "setAxis"/
    /// "setButton" plus whatever fields) is entirely up to whatever future
    /// layer interprets it; this class only guarantees valid JSON from an
    /// authenticated sender.
    void messageReceived(const QString &token, const QJsonObject &message);

private slots:
    void onNewConnection();
    void onReadyRead();
    void onSocketDisconnected();

private:
    struct ClientState
    {
        QString token;      ///< Empty until handleAuthMessage() accepts one.
        bool authenticated = false;
        QByteArray buffer;   ///< Bytes received since the last complete '\n'-terminated line.
        QTimer *authTimeoutTimer = nullptr;
    };

    /// Splits buffer on '\n' as bytes arrive, dispatching each complete line
    /// to handleLine() - a script's own JSON payload never legitimately
    /// contains a raw newline (QJsonDocument::Compact never emits one), so a
    /// plain byte search is sufficient framing, no escaping needed.
    void onSocketBytesReady(QTcpSocket *socket);
    void handleLine(QTcpSocket *socket, const QByteArray &line);
    void handleAuthMessage(QTcpSocket *socket, const QJsonObject &json);
    void disconnectClient(QTcpSocket *socket);

    static constexpr int kAuthTimeoutMs = 5000;

    /// Defensive cap on how many bytes a single client's buffer may grow to
    /// while waiting for a '\n' - a misbehaving or hostile local process
    /// that never sends one would otherwise grow this unbounded. No
    /// legitimate Script Bridge message (axis/button state, a handful of
    /// short fields) comes close to this.
    static constexpr int kMaxLineBytes = 65536;

    QTcpServer *m_server = nullptr;
    QHash<QTcpSocket *, ClientState> m_clients;

    /// Tokens issued via registerScriptToken() and not yet revoked - the
    /// pool handleAuthMessage() checks an incoming token against. A token
    /// already in use by a connected client stays in this set too (removed
    /// only by unregisterScriptToken(), not by disconnection), so a script
    /// that briefly drops its TCP connection can reconnect with the same
    /// token instead of needing a fresh one from a full relaunch.
    QSet<QString> m_validTokens;
};
